import type { Park, ParkEnterprise } from './types';

export const PARKS: Park[] = [
  {
    id: 'digital',
    name: '数字要素产业园',
    focus: '数据要素流通、公共数据、隐私计算',
    summary:
      '面向数据要素型企业，覆盖授权运营、数据空间与产业数据治理。',
  },
  {
    id: 'robot',
    name: '机器人产业园',
    focus: '协作机器人、产线集成、具身智能',
    summary:
      '面向机器人本体、感知与系统集成企业，便于就近对接制造场景。',
  },
  {
    id: 'exhibition',
    name: '智能会展产业园',
    focus: '智慧场馆、数字展陈、观展服务',
    summary:
      '面向会展科技与空间数字化企业，服务场馆运营和活动承办。',
  },
];

export const PARK_ENTERPRISES: ParkEnterprise[] = [
  {
    id: 'ent-zumaix',
    parkId: 'digital',
    name: '筑脉科技',
    industry: '企业服务',
    stage: '成长期',
    peopleLabel: '42 人',
    status: 'in_service',
    summary: '为企业服务方提供机会理解、发现投放与服务办理工作台。',
    needs: '高新技术企业认定辅导、数据要素政策解读。',
  },
  {
    id: 'ent-beichen-data',
    parkId: 'digital',
    name: '北辰数联',
    industry: '公共数据运营',
    stage: '成长期',
    peopleLabel: '28 人',
    status: 'in_park',
    summary: '做区域公共数据授权运营与数据产品登记。',
    needs: '数据要素专项、合规评估与场景对接。',
  },
  {
    id: 'ent-yunshu',
    parkId: 'digital',
    name: '云枢计算',
    industry: '隐私计算',
    stage: '初创',
    peopleLabel: '16 人',
    status: 'in_service',
    summary: '提供数据空间与隐私计算节点，支持跨机构可用不可见。',
    needs: '科技型中小企业信用贷、知识产权布局。',
  },
  {
    id: 'ent-xiyuan',
    parkId: 'digital',
    name: '析元智能',
    industry: '数据治理',
    stage: '初创',
    peopleLabel: '11 人',
    status: 'pending',
    summary: '为园区和主管部门提供产业数据目录与质量治理。',
    needs: '专精特新培育政策、入园服务确认。',
  },
  {
    id: 'ent-jinmen',
    parkId: 'robot',
    name: '津门协作',
    industry: '协作机器人',
    stage: '成长期',
    peopleLabel: '67 人',
    status: 'in_service',
    summary: '研发轻型协作机器人本体，服务 3C 与汽车零部件产线。',
    needs: '研发加计扣除口径梳理、智能制造专项。',
  },
  {
    id: 'ent-weihang',
    parkId: 'robot',
    name: '纬航自动化',
    industry: '产线集成',
    stage: '规模化',
    peopleLabel: '120 人',
    status: 'in_park',
    summary: '做机器人工作站与产线改造，承接园区制造企业集成项目。',
    needs: '园区加速器配套、产业对接沙龙。',
  },
  {
    id: 'ent-qingju',
    parkId: 'robot',
    name: '青矩感知',
    industry: '机器视觉',
    stage: '成长期',
    peopleLabel: '35 人',
    status: 'in_park',
    summary: '提供工业视觉与力觉方案，补齐机器人感知能力。',
    needs: '科技创新专项、检测认证辅导。',
  },
  {
    id: 'ent-lingbo',
    parkId: 'robot',
    name: '凌波具身',
    industry: '具身智能',
    stage: '初创',
    peopleLabel: '9 人',
    status: 'pending',
    summary: '探索具身智能在仓储搬运与巡检中的落地。',
    needs: '路演对接、初创期场地与申报辅导。',
  },
  {
    id: 'ent-huitong',
    parkId: 'exhibition',
    name: '会通智慧',
    industry: '智慧场馆',
    stage: '成长期',
    peopleLabel: '54 人',
    status: 'in_service',
    summary: '为会展场馆提供预约、人流与设备联动系统。',
    needs: '智慧城市相关政策、场馆运营项目对接。',
  },
  {
    id: 'ent-zhanmai',
    parkId: 'exhibition',
    name: '展脉数字',
    industry: '数字展陈',
    stage: '成长期',
    peopleLabel: '23 人',
    status: 'in_park',
    summary: '做展项内容生产与数字孪生展陈，服务主题展和常设展。',
    needs: '文化科技融合专项、知识产权贯标。',
  },
  {
    id: 'ent-linjing',
    parkId: 'exhibition',
    name: '临境空间',
    industry: '空间数字化',
    stage: '初创',
    peopleLabel: '14 人',
    status: 'in_park',
    summary: '把会展空间做成可复用的数字化搭建方案。',
    needs: '中小企业服务、园区配套工位。',
  },
  {
    id: 'ent-guangnian',
    parkId: 'exhibition',
    name: '光年导览',
    industry: '观展服务',
    stage: '初创',
    peopleLabel: '8 人',
    status: 'pending',
    summary: '提供导览、预约与观众运营工具，面向中小型展览活动。',
    needs: '活动报名合作、早期团队辅导。',
  },
];
