import type { OpportunityWarehouseItem } from './types';

export const OPPORTUNITY_WAREHOUSE_ITEMS: OpportunityWarehouseItem[] = [
  {
    id: 'own-gaoxin',
    title: '高新技术企业认定辅导',
    kind: 'own_service',
    publisher: '筑脉企服',
    summary:
      '面向成长型科技企业的认定辅导：材料梳理、指标对照与申报节奏，由服务方直接办理。',
    audience: '本企业服务对象，可投放到小程序「为你发现」。',
    origin: 'curated',
    status: 'ready',
    sourceLabel: '服务方整理入库',
    updatedAtLabel: '昨天',
  },
  {
    id: 'own-ip',
    title: '知识产权贯标与布局',
    kind: 'own_service',
    publisher: '筑脉企服',
    summary:
      '专利、商标与贯标辅导的组合服务。仍在整理适用边界，暂不投放。',
    audience: '有知识产权基础建设需求的企业。',
    origin: 'curated',
    status: 'draft',
    sourceLabel: '服务方整理入库',
    updatedAtLabel: '周一',
  },
  {
    id: 'policy-kjzx',
    title: '2026 年度科技创新专项',
    kind: 'policy',
    publisher: '市科技局',
    summary:
      '支持研发投入、项目立项与配套资金的年度专项。采集自公开政策页，待服务方核对适用对象后投放。',
    audience: '符合申报条件的科技型企业。',
    origin: 'capture',
    status: 'needs_review',
    sourceLabel: '公开政策页',
    captureUrl: 'https://example.gov.cn/kjzx-2026',
    updatedAtLabel: '今天 09:20',
  },
  {
    id: 'policy-zxjx',
    title: '专精特新中小企业培育',
    kind: 'policy',
    publisher: '工信主管部门',
    summary:
      '专精特新梯度培育与认定指引。已经过整理，可按企业画像投放到小程序。',
    audience: '制造业与硬科技方向的中小企业。',
    origin: 'curated',
    status: 'ready',
    sourceLabel: '机构公开文件',
    updatedAtLabel: '9月12日',
  },
  {
    id: 'vendor-loan',
    title: '科技型中小企业信用贷对接',
    kind: 'vendor_service',
    publisher: '合作金融机构',
    summary:
      '服务商提供的信贷对接，不替代筑脉自有办理。入库后由服务方决定是否推荐给匹配企业。',
    audience: '有短期资金周转需求的科技型中小企业。',
    origin: 'curated',
    status: 'ready',
    sourceLabel: '服务商提供',
    updatedAtLabel: '9月10日',
  },
  {
    id: 'vendor-park',
    title: '园区加速器入驻服务',
    kind: 'vendor_service',
    publisher: '合作产业园区',
    summary:
      '工位、加速营与园区配套。采集自园区公开页，还需确认名额与合作口径。',
    audience: '需要物理空间或园区资源的早期团队。',
    origin: 'capture',
    status: 'needs_review',
    sourceLabel: '园区公开页',
    captureUrl: 'https://example-park.cn/accelerator',
    updatedAtLabel: '今天 08:04',
  },
  {
    id: 'event-salon',
    title: '产业对接沙龙 · 9 月场',
    kind: 'event',
    publisher: '筑脉企服',
    summary:
      '小范围产业对接活动。适合作为「为你发现」中的限时内容，而不是长期服务事项。',
    audience: '关注产业协作与当面沟通的企业联系人。',
    origin: 'curated',
    status: 'ready',
    sourceLabel: '服务方整理入库',
    updatedAtLabel: '昨天',
  },
  {
    id: 'event-roadshow',
    title: '投融资路演周',
    kind: 'event',
    publisher: '合作投融资机构',
    summary:
      '路演与资本对接周。采集到标题后尚未核对时间与报名方式。',
    audience: '有融资计划的项目团队。',
    origin: 'capture',
    status: 'draft',
    sourceLabel: '活动公开页',
    captureUrl: 'https://example-capital.cn/roadshow',
    updatedAtLabel: '上周',
  },
];
