import type { CrawlJob, CrawlLogEntry, WhitelistSite } from './types';

export const WHITELIST_SITES: WhitelistSite[] = [
  {
    id: 'wl-kjj',
    host: 'kjj.example.gov.cn',
    name: '市科技局',
    kind: 'policy',
    enabled: true,
    robots: 'allowed',
    allowPath: '/zhengce',
    addedAtLabel: '9月3日',
    note: '仅政策栏目。跳过登录与个人中心。',
  },
  {
    id: 'wl-jxj',
    host: 'jxj.example.gov.cn',
    name: '市经信局',
    kind: 'policy',
    enabled: true,
    robots: 'allowed',
    allowPath: '/zxjx',
    addedAtLabel: '9月3日',
    note: '专精特新与中小企业政策页。',
  },
  {
    id: 'wl-sme',
    host: 'sme.example.gov.cn',
    name: '中小企业服务网',
    kind: 'policy',
    enabled: true,
    robots: 'allowed',
    allowPath: '/',
    addedAtLabel: '9月8日',
    note: '公开服务与申报入口，不含咨询表单提交。',
  },
  {
    id: 'wl-park',
    host: 'park.example.cn',
    name: '合作产业园区',
    kind: 'event',
    enabled: true,
    robots: 'restricted',
    allowPath: '/open',
    addedAtLabel: '9月10日',
    note: 'robots.txt 限制 /events。活动页需改从 /open 采集。',
  },
  {
    id: 'wl-capital',
    host: 'capital.example.cn',
    name: '合作投融资机构',
    kind: 'event',
    enabled: true,
    robots: 'allowed',
    allowPath: '/public',
    addedAtLabel: '9月12日',
    note: '只采公开路演与日程，不采报名后台。',
  },
  {
    id: 'wl-bank',
    host: 'bank.example.cn',
    name: '合作金融机构',
    kind: 'vendor',
    enabled: false,
    robots: 'restricted',
    allowPath: '/sme',
    addedAtLabel: '9月14日',
    note: '服务条款待核对，默认停用。',
  },
];

export const CRAWL_JOBS: CrawlJob[] = [
  {
    id: 'job-kjj',
    title: '市科技局 · 政策栏目',
    whitelistId: 'wl-kjj',
    startUrl: 'https://kjj.example.gov.cn/zhengce',
    status: 'running',
    fetched: 86,
    planned: 134,
    stored: 4,
    skipped: 11,
    failedPages: 0,
    intervalSec: 2,
    depth: 2,
    lastHttp: '200 · 138ms',
    startedAtLabel: '今天 09:12',
    updatedAtLabel: '12 秒前',
  },
  {
    id: 'job-jxj',
    title: '经信局 · 专精特新',
    whitelistId: 'wl-jxj',
    startUrl: 'https://jxj.example.gov.cn/zxjx',
    status: 'completed',
    fetched: 52,
    planned: 52,
    stored: 2,
    skipped: 6,
    failedPages: 0,
    intervalSec: 2,
    depth: 1,
    lastHttp: '200 · 121ms',
    startedAtLabel: '今天 08:03',
    updatedAtLabel: '今天 08:41',
  },
  {
    id: 'job-park',
    title: '园区公开活动',
    whitelistId: 'wl-park',
    startUrl: 'https://park.example.cn/events',
    status: 'failed',
    fetched: 12,
    planned: 40,
    stored: 0,
    skipped: 8,
    failedPages: 9,
    intervalSec: 3,
    depth: 1,
    lastHttp: '403 · robots Disallow',
    startedAtLabel: '今天 08:20',
    updatedAtLabel: '今天 08:26',
  },
  {
    id: 'job-sme',
    title: '中小企业服务网',
    whitelistId: 'wl-sme',
    startUrl: 'https://sme.example.gov.cn/',
    status: 'paused',
    fetched: 20,
    planned: 90,
    stored: 1,
    skipped: 4,
    failedPages: 0,
    intervalSec: 2,
    depth: 2,
    lastHttp: '200 · 156ms',
    startedAtLabel: '昨天 16:40',
    updatedAtLabel: '昨天 16:58',
  },
  {
    id: 'job-bank',
    title: '合作银行产品页',
    whitelistId: 'wl-bank',
    startUrl: 'https://bank.example.cn/sme',
    status: 'queued',
    fetched: 0,
    planned: 24,
    stored: 0,
    skipped: 0,
    failedPages: 0,
    intervalSec: 3,
    depth: 1,
    lastHttp: '未开始',
    startedAtLabel: '—',
    updatedAtLabel: '今天 09:01',
  },
];

export const CRAWL_LOGS: CrawlLogEntry[] = [
  {
    id: 'log-01',
    at: '09-16 08:20:11',
    jobId: 'job-park',
    level: 'info',
    message: '启动任务  起点 https://park.example.cn/events  depth=1  interval=3s',
  },
  {
    id: 'log-02',
    at: '09-16 08:20:12',
    jobId: 'job-park',
    level: 'warn',
    message: 'robots.txt  Disallow: /events  将尝试白名单路径 /open',
  },
  {
    id: 'log-03',
    at: '09-16 08:20:18',
    jobId: 'job-park',
    level: 'error',
    message: 'GET https://park.example.cn/events  403  被站点拒绝，本轮失败 9 页',
  },
  {
    id: 'log-04',
    at: '09-16 08:03:04',
    jobId: 'job-jxj',
    level: 'info',
    message: '启动任务  起点 https://jxj.example.gov.cn/zxjx  遵守 robots.txt',
  },
  {
    id: 'log-05',
    at: '09-16 08:18:22',
    jobId: 'job-jxj',
    level: 'info',
    message: 'GET https://jxj.example.gov.cn/zxjx/2026-01  200  119ms  写入待整理',
  },
  {
    id: 'log-06',
    at: '09-16 08:41:07',
    jobId: 'job-jxj',
    level: 'info',
    message: '任务完成  fetched=52  stored=2  skipped=6  已进入机会库待整理',
  },
  {
    id: 'log-07',
    at: '09-16 09:12:01',
    jobId: 'job-kjj',
    level: 'info',
    message: '启动任务  起点 https://kjj.example.gov.cn/zhengce  depth=2  interval=2s',
  },
  {
    id: 'log-08',
    at: '09-16 09:12:03',
    jobId: 'job-kjj',
    level: 'info',
    message: '白名单命中  host=kjj.example.gov.cn  allow=/zhengce',
  },
  {
    id: 'log-09',
    at: '09-16 09:14:18',
    jobId: 'job-kjj',
    level: 'warn',
    message: 'skip https://kjj.example.gov.cn/login  非公开入口',
  },
  {
    id: 'log-10',
    at: '09-16 09:15:02',
    jobId: 'job-kjj',
    level: 'warn',
    message: 'skip https://news.example.gov.cn/kj  主机不在白名单',
  },
  {
    id: 'log-11',
    at: '09-16 09:16:44',
    jobId: 'job-kjj',
    level: 'info',
    message: 'GET https://kjj.example.gov.cn/zhengce/2026-kjzx  200  142ms  解析到政策标题',
  },
  {
    id: 'log-12',
    at: '09-16 09:18:09',
    jobId: 'job-kjj',
    level: 'info',
    message: '写入机会库待整理  「2026 年度科技创新专项」',
  },
  {
    id: 'log-13',
    at: '09-16 09:18:51',
    jobId: 'job-kjj',
    level: 'info',
    message: 'GET https://kjj.example.gov.cn/zhengce/r-d-voucher  200  138ms  进度 86/134',
  },
  {
    id: 'log-14',
    at: '09-15 16:58:12',
    jobId: 'job-sme',
    level: 'info',
    message: '操作员暂停  已抓 20/90  下次从断点继续',
  },
  {
    id: 'log-15',
    at: '09-16 09:01:20',
    jobId: 'job-bank',
    level: 'warn',
    message: '站点 bank.example.cn 已停用  任务保持排队，不会发请求',
  },
];
